name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github-actions
        chmod 600 ~/.ssh/github-actions

    - name: Add EC2 (via DuckDNS) to known hosts
      run: |
        ssh-keyscan -H leavemanager.duckdns.org >> ~/.ssh/known_hosts

    - name: Deploy to EC2 via SSH
      run: |
         ssh -i ~/.ssh/github-actions ubuntu@leavemanager.duckdns.org << 'EOF'
          cd /var/www/html
           git reset --hard
           git pull origin main
            sudo systemctl restart apache2
          EOF


