name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github-actions
        chmod 600 ~/.ssh/github-actions

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H 16.171.232.230 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/github-actions ubuntu@16.171.232.230 << 'EOF'
          cd /var/www/html/leavemanager   # Update if your path is different
          git pull origin main
        EOF
